name: Watch repo visibility

on:
  schedule:
    - cron: "0 */6 * * *"   # run every 6 hours
  workflow_dispatch: {}      # allow manual trigger

jobs:
  watch:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          # use a PAT so we can push changes back
          token: ${{ secrets.GH_PAT }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Run watcher
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          # Reuse GH_PAT for both GitHub API auth (rate limit)
          # and for authenticated push.
          GITHUB_API_TOKEN: ${{ secrets.GH_PAT }}
          GIT_REMOTE_URL: https://${{ secrets.GH_PAT }}@github.com/${{ github.repository }}.git
        run: |
          python watcher.py
      - name: Log timestamp
        run: |
          date
          echo "Workflow triggered by event ${{ github.event_name }}"

